
services:
  - type: web
    name: endurance-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: endurance-db
          property: connectionStringInternal
      - key: WEBADOR_ORIGIN
        value: "https://ton-site.webador.com"  # adapte

  - type: worker
    name: endurance-worker-finished
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/worker_finished.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: endurance-db
          property: connectionStringInternal

  - type: cron
    name: endurance-cron
    env: python
    schedule: "*/10 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python app/recompute_indices.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: endurance-db
          property: connectionStringInternal

databases:
  - name: endurance-db
    plan: free

